"""Add image_src to Person

Revision ID: 0126185bc7bc
Revises: 0ef8483d69d1
Create Date: 2025-09-05 20:56:06.673290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0126185bc7bc'
down_revision = '0ef8483d69d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_src', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('image_src')

    # ### end Alembic commands ###
