"""add id to tag relation

Revision ID: 2147134cf348
Revises: 787e83b09b84
Create Date: 2025-08-06 22:51:38.027648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2147134cf348'
down_revision = '787e83b09b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_tag', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
