"""more fields for quote

Revision ID: 41cd97349726
Revises: 64a32fb55823
Create Date: 2026-04-03 12:51:49.024863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cd97349726'
down_revision = '64a32fb55823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_source', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('orig_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('orig_lang', sa.String(length=2), nullable=True))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('PARTY', 'REGION', 'ORGANIZATION', name='tagcategory'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('PARTY', 'REGION', 'ORGANIZATION', name='tagcategory'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)

    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('orig_lang')
        batch_op.drop_column('orig_text')
        batch_op.drop_column('secondary_source')

    # ### end Alembic commands ###
