"""Remove VisitStat from main database

Revision ID: 58acf1b52f5e
Revises: 0126185bc7bc
Create Date: 2025-09-22 16:28:29.765798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58acf1b52f5e'
down_revision = '0126185bc7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_stat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_stat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ip_hash', sa.VARCHAR(length=20), nullable=False),
    sa.Column('path', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_hash', 'path', 'date', name=op.f('unique_ip_path_date'))
    )
    # ### end Alembic commands ###
