"""tag_categories and person_tags

Revision ID: 64a32fb55823
Revises: 22bca00a5b8e
Create Date: 2026-04-02 23:12:48.350057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a32fb55823'
down_revision = '22bca00a5b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('PARTY', 'REGION', name='tagcategory'), nullable=True))
        batch_op.add_column(sa.Column('custom_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('custom_info')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
