"""Add related_quotes table

Revision ID: b220feb776ee
Revises: a67a5d9f3753
Create Date: 2025-07-29 20:35:34.808240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b220feb776ee'
down_revision = 'a67a5d9f3753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_meta_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_quote_a_id', sa.Integer(), nullable=False),
    sa.Column('meta_quote_b_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=False),
    sa.ForeignKeyConstraint(['meta_quote_a_id'], ['meta_quote.id'], ),
    sa.ForeignKeyConstraint(['meta_quote_b_id'], ['meta_quote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_meta_quotes')
    # ### end Alembic commands ###
